services:
  app:
    image: procsiab/crater-app:v1.2-amd64
    ports:
      - '9000:9000'
    volumes:
      - app-share:/var/www:z
  db:
    image: amd64/mariadb:10.7.3-focal
    volumes:
      - ./data:/var/lib/mysql/data:Z
    environment:
      - MYSQL_USER=crater
      - MYSQL_PASSWORD=crater
      - MYSQL_DATABASE=crater
      - MYSQL_ROOT_PASSWORD=crater
    ports:
      - '15432:5432'
  web:
    image: amd64/nginx:1.21.6-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d/:Z
      - app-share:/var/www:z

volumes:
  app-share:
